### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by brunoscota** [NetDocuments/ad-join-cookbook#26]
Hello, I tried to execute but its failing with this error:

" [2017-06-08T02:11:00+00:00] FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'ad-join' version '4.12.1' depends on chef version ["~> 12"], but the running chef version is 13.1.31"

info: I wrapped this cookbook to my own cookbook.
help me.

**Comment by spuder** [comment]
Yes, this cookbook doesn't work with Chef 13 yet because of a bug in chef 13 around the scheduled tasks. See issue #23 

The work around is to bootstrap your nodes with chef 12.

    knife bootstrap --bootstrap-version 12.20.3

 If you know anyone at chef, you could ask them to please get this bug fixed. https://github.com/chef/chef/issues/6059. 

Closing in favor of issue #23

**Comment by brunoscota** [comment]
Thank you, worked!
